import Header from "../components/Header";
import "../styles/globals.css";
import PromptInput from "../components/PromptInput";

export const metadata = {
  title: "ai image generator",
  description: "Find images generated by Dall-e and open ai.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <PromptInput />
        {children}
      </body>
    </html>
  );
}
