import Header from "../components/Header";
import "../styles/globals.css";
import PromptInput from "../components/PromptInput";
import ClientProvider from "../components/ClientProvider";

export const metadata = {
  title: "ai image generator",
  description: "Find images generated by Dall-e and open ai.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>
          <Header />
          <PromptInput />
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
